socialmedia/account/urls.py
from django.urls import path
from . import views


app_name = "account"
urlpatterns = [
    path("register/", views.UserRegistrationView.as_view(), name="user_register"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    path("profile/<int:user_id>", views.UserProfileView.as_view(), name="user_profile"),
    path("community/", views.CommunityView.as_view(), name="user_community"),
    path("reset/", views.UserPasswordResetView.as_view(), name="reset"),
    path("reset/done", views.UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("confirm/<uidb64>/<token>", views.UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("complete/", views.UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("follow/<int:user_id>/", views.UserFollowView.as_view(), name="user_follow"),
    path("unfollow/<int:user_id>/", views.UserUnfollowView.as_view(), name="user_unfollow"),
    path("edit_profile/", views.EditProfileView.as_view() ,name="user_edit_profile"),
]

socialmedia/home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("posts/<int:post_id>/<slug:post_slug>", views.PostDetailView.as_view(), name="post_detail"),
    path("post/delete/<int:post_id>/", views.PostDeleteView.as_view(), name="post_delete"),
    path("post/update/<int:post_id>/", views.PostUpdateView.as_view(), name="post_update"),
    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path("reply/<int:post_id>/<int:comment_id>/", views.ReplyAddView.as_view(), name="post_reply"),
    path("like/<int:post_id>/", views.PostLikeView.as_view(), name="post_like")
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account"))
]

socialmedia/templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}
        
        <p class="alert alert-{{msg.tags}}"> {{msg}} </p>

    {% endfor %}

{% endif %}

socialmedia/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">ASAMA</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
          
        
          {% if request.user.is_authenticated %}

          <a class="nav-link" href="{%  url 'account:user_profile' request.user.id %}">Profile</a>
          <a class="nav-link" href="{%  url 'account:user_community'  %}">Community</a>
          <a class="nav-link" href="{%  url 'account:user_logout' %}">Logout</a>

          {% else %}
          
          <a class="nav-link" href="{% url 'account:user_register' %}">Register</a>
          <a class="nav-link" href="{% url 'account:user_login' %}">Login</a>

          {% endif %}
          
        </div>
      </div>
    </div>
  </nav>