socialmedia/account/urls.py
from django.urls import path
from . import views


app_name = "account"
urlpatterns = [
    path("register/", views.UserRegistrationView.as_view(), name="user_register"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    path("profile/<int:user_id>", views.UserProfileView.as_view(), name="user_profile"),
    path("community/", views.CommunityView.as_view(), name="user_community"),
    path("reset/", views.UserPasswordResetView.as_view(), name="reset"),
    path("reset/done", views.UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("confirm/<uidb64>/<token>", views.UserPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("complete/", views.UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("follow/<int:user_id>/", views.UserFollowView.as_view(), name="user_follow"),
    path("unfollow/<int:user_id>/", views.UserUnfollowView.as_view(), name="user_unfollow"),
    path("edit_profile/", views.EditProfileView.as_view() ,name="user_edit_profile"),
]

socialmedia/home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("posts/<int:post_id>/<slug:post_slug>", views.PostDetailView.as_view(), name="post_detail"),
    path("post/delete/<int:post_id>/", views.PostDeleteView.as_view(), name="post_delete"),
    path("post/update/<int:post_id>/", views.PostUpdateView.as_view(), name="post_update"),
    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path("reply/<int:post_id>/<int:comment_id>/", views.ReplyAddView.as_view(), name="post_reply"),
    path("like/<int:post_id>/", views.PostLikeView.as_view(), name="post_like")
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account"))
]

socialmedia/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=50)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-updated", "-date_posted")

    def __str__(self) -> str:
        return f"{self.title} - {self.user}"
    
    def get_absolute_url(self):
        return reverse("home:post_detail", args=(self.id, self.slug))
    
    def like_count(self):
        return  self.pvote.count()
    
    def user_can_like(self, user):
         user_like = user.uvote.filter(post=self)
         if user_like.exists():
             return True
         return False
    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ucomment")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pcomment")
    reply = models.ForeignKey("self", on_delete=models.CASCADE, related_name="rcomment", blank=True, null=True)
    body = models.TextField()
    is_reply = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.body[:30]}"
    

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="uvote")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pvote")

    def __str__(self) -> str:
        return f"{self.user} - {self.post}"

socialmedia/home/forms.py
from django import forms
from .models import Post, Comment

class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content",)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {
            "body": forms.Textarea(attrs={"class":"form-control"})
        }

class ReplyAddForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)


class  SearchPostForm(forms.Form):
    search = forms.CharField(max_length=200)

socialmedia/home/views.py
from typing import Any
from django.http import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Post, Comment, Vote
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostCreateUpdateForm, CommentCreateForm, ReplyAddForm, SearchPostForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class HomeView(View):
    form = SearchPostForm

    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get("search"):
            posts = posts.filter(content__contains=request.GET["search"])
        return render(request, "home/home.html", {"posts": posts, "form": self.form})
    

class PostDetailView(View):
    form = CommentCreateForm
    reply_form = ReplyAddForm

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.post_instance = Post.objects.get(pk=kwargs["post_id"], slug=kwargs["post_slug"])
        return super().setup(request, *args, **kwargs)


    def get(self, request, *args, **kwargs):
        # user = User.objects.get(pk=post)
        comments = self.post_instance.pcomment.filter(is_reply=False)
        user_can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            user_can_like = True
        return render(request, "home/post_detail.html", {"post": self.post_instance, "comments": comments, "form": self.form, "reply_form": self.reply_form, "user_can_like": user_can_like})
    
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, "Your Comment Submitted successfull", extra_tags="success")
            return redirect("home:post_detail", self.post_instance.id, self.post_instance.slug)

        
    
class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post_delete = get_object_or_404(Post, pk=post_id)
        if post_delete.user.id == request.user.id:
            post_delete.delete()
            messages.success(request, "Your Post Deleted Successfully", extra_tags="success")
        else:
            messages.error(request, "Your Post Wasn't Deleted", extra_tags="danger")
    
        return redirect("home:home")
    

class PostUpdateView(LoginRequiredMixin, View):
    form = PostCreateUpdateForm

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.post_instance = Post.objects.get(pk=kwargs["post_id"])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        post_update = self.post_instance
        if not request.user.id == post_update.user.id:
            messages.error(request, "You Cant Update This Post")
            return redirect("home:home")

        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form(instance=post)
        return render(request, "home/update.html", {"form": form})
    
    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data["content"][:30])
            new_post.save()
            messages.success(request, "Your Post Updated")
            return redirect("home:post_detail", post.id, post.slug)

class PostCreateView(LoginRequiredMixin, View):
    form = PostCreateUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form
        return render(request, "home/post_create.html", {"form": form})
    
    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data["content"][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, "You Create a New Post", extra_tags="success")
            return redirect("home:post_detail", new_post.id, new_post.slug)
        

class ReplyAddView(LoginRequiredMixin, View):
    

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, pk=post_id)
        comment = get_object_or_404(Comment, pk=comment_id)
        form = ReplyAddForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, "Your Reply Submitted Successfully", extra_tags="success")

        return redirect("home:post_detail",  post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote.objects.filter(post=post, user=request.user)
        if like.exists():
            messages.error(request, "You Hve Already This Post", extra_tags="danger")
        else:
            Vote.objects.create(user=request.user, post=post)
            messages.success(request, "You Liked This Post")

        return redirect("home:post_detail", post.id, post.slug)

socialmedia/home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}

    <h1>
        Home Pages...
    </h1><br/>

        <form action="" method="get">

            {{form.as_p}}
            <input type="submit" value="Search">

        </form><br/>

        {% for post in posts %}

         <p>
            
            <a href="{{ post.get_absolute_url }}"> {{post.title}} </a>

            <p>
                {{post.content}}
            </p>

         </p><hr>

        {% endfor %}


{% endblock %}

socialmedia/home/templates/home/post_create.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post" novalidate>

        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" value="Create">

    </form>

{% endblock %}

socialmedia/home/templates/home/post_detail.html
{% extends 'base.html' %}


{% block content %}

        <h1> {{post.title}} </h1>
        <small> {{post.date_posted}} </small>
        <p> {{post.content}} </p>
        
        <small> 
            Author: <a href="{% url 'account:user_profile' post.user.id %}"> {{post.user}} </a>
             
        </small>

        {% if request.user.id == post.user.id %}
        
        <br>
        <br>
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger" > Delete </a>
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-warning" > Update </a>

        {% endif %}

        <hr>


        {% if request.user.is_authenticated %}

            <a href="{% url 'home:post_like' post.id %}" class="{% if user_can_like %} disabled {% endif %} btn btn-primary col-md-2"> Like {{post.like_count}} </a>

            <form action="" method="post" novalidate>

                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Send">

            </form>

        {% else %}
            
            <p class="alert alert-danger">
                You Not Logged in So You Cant Comment On This Post.
            </p>

        {% endif %}



        {% for comment in comments %}

            <div class="card bg-dark text-white">

                <p class="card-header">
                    {{comment.user}} | {{comment.created | timesince}} ago
                </p>

                <p class="card-body">
                    {{comment.body}}
                </p>

            {% if request.user.is_authenticated %}


                <form action="{% url 'home:post_reply' post.id comment.id %}" method="post" novalidate>

                    {% csrf_token %}
                    {{reply_form.as_p}}
                    <input type="submit" value="Send">

                </form>

            {% endif %}

            {% for reply in comment.rcomment.all %}

                <p class="bg-primary p-3 m-2">
                    {{reply.user}} | {{reply.body}}
                </p>

            {% endfor %}

            </div>

            {% empty %}
                <p>
                    No Comments Yet! Be the first to comment on this Post.
                </p>



        {% endfor %}

        
        

{% endblock %}

socialmedia/home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post" novalidate>

        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" value="Update">

    </form>

{% endblock %}